// ==============================================================================
// src/types/database.ts
// Nepal Hemophilia Society — TypeScript Database Interface for Supabase
// ==============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole =
  | 'super_admin'
  | 'admin'
  | 'provincial_admin'
  | 'editor'
  | 'healthcare_professional'
  | 'member'
  | 'viewer';

export interface Database {
  public: {
    Tables: {
      provinces: {
        Row: {
          id: string;
          code: number;
          name_en: string;
          name_ne: string;
          description_en: string | null;
          description_ne: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: number;
          name_en: string;
          name_ne: string;
          description_en?: string | null;
          description_ne?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: number;
          name_en?: string;
          name_ne?: string;
          description_en?: string | null;
          description_ne?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string | null;
          role: UserRole;
          province_id: string | null;
          hospital_affiliation: string | null;
          avatar_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          email: string;
          phone?: string | null;
          role?: UserRole;
          province_id?: string | null;
          hospital_affiliation?: string | null;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          phone?: string | null;
          role?: UserRole;
          province_id?: string | null;
          hospital_affiliation?: string | null;
          avatar_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      provincial_chapters: {
        Row: {
          id: string;
          province_id: string | null;
          chapter_name: string;
          chairperson: string | null;
          contact_person: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          description_en: string | null;
          description_ne: string | null;
          image_url: string | null;
          status: string;
          is_deleted: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          province_id?: string | null;
          chapter_name: string;
          chairperson?: string | null;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          description_en?: string | null;
          description_ne?: string | null;
          image_url?: string | null;
          status?: string;
          is_deleted?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          province_id?: string | null;
          chapter_name?: string;
          chairperson?: string | null;
          contact_person?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          description_en?: string | null;
          description_ne?: string | null;
          image_url?: string | null;
          status?: string;
          is_deleted?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      treatment_centres: {
        Row: {
          id: string;
          name_en: string;
          name_ne: string;
          province_id: string | null;
          hospital_type: string;
          address_en: string | null;
          address_ne: string | null;
          phone: string | null;
          emergency_phone: string | null;
          email: string | null;
          latitude: number | null;
          longitude: number | null;
          hematologist_in_charge_en: string | null;
          hematologist_in_charge_ne: string | null;
          services: string[] | null;
          factor_viii_available: boolean;
          factor_ix_available: boolean;
          pediatric_care: boolean;
          emergency_service: boolean;
          is_verified: boolean;
          status: string;
          is_deleted: boolean;
          display_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name_en: string;
          name_ne: string;
          province_id?: string | null;
          hospital_type?: string;
          address_en?: string | null;
          address_ne?: string | null;
          phone?: string | null;
          emergency_phone?: string | null;
          email?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          hematologist_in_charge_en?: string | null;
          hematologist_in_charge_ne?: string | null;
          services?: string[] | null;
          factor_viii_available?: boolean;
          factor_ix_available?: boolean;
          pediatric_care?: boolean;
          emergency_service?: boolean;
          is_verified?: boolean;
          status?: string;
          is_deleted?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name_en?: string;
          name_ne?: string;
          province_id?: string | null;
          hospital_type?: string;
          address_en?: string | null;
          address_ne?: string | null;
          phone?: string | null;
          emergency_phone?: string | null;
          email?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          hematologist_in_charge_en?: string | null;
          hematologist_in_charge_ne?: string | null;
          services?: string[] | null;
          factor_viii_available?: boolean;
          factor_ix_available?: boolean;
          pediatric_care?: boolean;
          emergency_service?: boolean;
          is_verified?: boolean;
          status?: string;
          is_deleted?: boolean;
          display_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      factor_inventory: {
        Row: {
          id: string;
          treatment_centre_id: string;
          factor_type: string;
          brand: string | null;
          strength: string | null;
          batch_number: string | null;
          quantity: number;
          unit: string;
          expiry_date: string | null;
          storage_temperature: string;
          cold_chain_verified: boolean;
          status: string;
          last_verified_at: string;
          verified_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          treatment_centre_id: string;
          factor_type: string;
          brand?: string | null;
          strength?: string | null;
          batch_number?: string | null;
          quantity?: number;
          unit?: string;
          expiry_date?: string | null;
          storage_temperature?: string;
          cold_chain_verified?: boolean;
          status?: string;
          last_verified_at?: string;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          treatment_centre_id?: string;
          factor_type?: string;
          brand?: string | null;
          strength?: string | null;
          batch_number?: string | null;
          quantity?: number;
          unit?: string;
          expiry_date?: string | null;
          storage_temperature?: string;
          cold_chain_verified?: boolean;
          status?: string;
          last_verified_at?: string;
          verified_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      notices: {
        Row: {
          id: string;
          title_en: string;
          title_ne: string;
          content_en: string;
          content_ne: string;
          notice_type: string;
          priority: string;
          image_url: string | null;
          file_url: string | null;
          is_published: boolean;
          is_deleted: boolean;
          published_at: string;
          expires_at: string | null;
          target_audience: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_ne: string;
          content_en: string;
          content_ne: string;
          notice_type?: string;
          priority?: string;
          image_url?: string | null;
          file_url?: string | null;
          is_published?: boolean;
          is_deleted?: boolean;
          published_at?: string;
          expires_at?: string | null;
          target_audience?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title_en?: string;
          title_ne?: string;
          content_en?: string;
          content_ne?: string;
          notice_type?: string;
          priority?: string;
          image_url?: string | null;
          file_url?: string | null;
          is_published?: boolean;
          is_deleted?: boolean;
          published_at?: string;
          expires_at?: string | null;
          target_audience?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      posts: {
        Row: {
          id: string;
          title_en: string;
          title_ne: string;
          slug: string;
          excerpt_en: string | null;
          excerpt_ne: string | null;
          content_en: string;
          content_ne: string;
          featured_image: string | null;
          category: string;
          author: string | null;
          read_time: string;
          tags: string[] | null;
          is_featured: boolean;
          is_published: boolean;
          is_deleted: boolean;
          consent_verified: boolean;
          display_order: number;
          published_at: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_ne: string;
          slug: string;
          excerpt_en?: string | null;
          excerpt_ne?: string | null;
          content_en: string;
          content_ne: string;
          featured_image?: string | null;
          category?: string;
          author?: string | null;
          read_time?: string;
          tags?: string[] | null;
          is_featured?: boolean;
          is_published?: boolean;
          is_deleted?: boolean;
          consent_verified?: boolean;
          display_order?: number;
          published_at?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title_en?: string;
          title_ne?: string;
          slug?: string;
          excerpt_en?: string | null;
          excerpt_ne?: string | null;
          content_en?: string;
          content_ne?: string;
          featured_image?: string | null;
          category?: string;
          author?: string | null;
          read_time?: string;
          tags?: string[] | null;
          is_featured?: boolean;
          is_published?: boolean;
          is_deleted?: boolean;
          consent_verified?: boolean;
          display_order?: number;
          published_at?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title_en: string;
          title_ne: string;
          description_en: string | null;
          description_ne: string | null;
          event_type: string;
          start_date: string;
          end_date: string | null;
          location_en: string | null;
          location_ne: string | null;
          province_id: string | null;
          organizer: string | null;
          registration_enabled: boolean;
          registration_url: string | null;
          capacity: number | null;
          image_url: string | null;
          is_published: boolean;
          is_deleted: boolean;
          display_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_ne: string;
          description_en?: string | null;
          description_ne?: string | null;
          event_type?: string;
          start_date: string;
          end_date?: string | null;
          location_en?: string | null;
          location_ne?: string | null;
          province_id?: string | null;
          organizer?: string | null;
          registration_enabled?: boolean;
          registration_url?: string | null;
          capacity?: number | null;
          image_url?: string | null;
          is_published?: boolean;
          is_deleted?: boolean;
          display_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title_en?: string;
          title_ne?: string;
          description_en?: string | null;
          description_ne?: string | null;
          event_type?: string;
          start_date?: string;
          end_date?: string | null;
          location_en?: string | null;
          location_ne?: string | null;
          province_id?: string | null;
          organizer?: string | null;
          registration_enabled?: boolean;
          registration_url?: string | null;
          capacity?: number | null;
          image_url?: string | null;
          is_published?: boolean;
          is_deleted?: boolean;
          display_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      resources: {
        Row: {
          id: string;
          title_en: string;
          title_ne: string;
          description_en: string | null;
          description_ne: string | null;
          category: string;
          resource_type: string;
          file_url: string | null;
          file_size: string | null;
          file_format: string | null;
          thumbnail_url: string | null;
          author: string | null;
          publication_date: string | null;
          download_count: number;
          is_published: boolean;
          is_deleted: boolean;
          display_order: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title_en: string;
          title_ne: string;
          description_en?: string | null;
          description_ne?: string | null;
          category?: string;
          resource_type?: string;
          file_url?: string | null;
          file_size?: string | null;
          file_format?: string | null;
          thumbnail_url?: string | null;
          author?: string | null;
          publication_date?: string | null;
          download_count?: number;
          is_published?: boolean;
          is_deleted?: boolean;
          display_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title_en?: string;
          title_ne?: string;
          description_en?: string | null;
          description_ne?: string | null;
          category?: string;
          resource_type?: string;
          file_url?: string | null;
          file_size?: string | null;
          file_format?: string | null;
          thumbnail_url?: string | null;
          author?: string | null;
          publication_date?: string | null;
          download_count?: number;
          is_published?: boolean;
          is_deleted?: boolean;
          display_order?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      healthcare_professionals: {
        Row: {
          id: string;
          full_name_en: string;
          full_name_ne: string;
          designation_en: string | null;
          designation_ne: string | null;
          specialization: string | null;
          institution_en: string | null;
          institution_ne: string | null;
          province_id: string | null;
          phone: string | null;
          email: string | null;
          photo_url: string | null;
          bio_en: string | null;
          bio_ne: string | null;
          display_order: number;
          is_deleted: boolean;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name_en: string;
          full_name_ne: string;
          designation_en?: string | null;
          designation_ne?: string | null;
          specialization?: string | null;
          institution_en?: string | null;
          institution_ne?: string | null;
          province_id?: string | null;
          phone?: string | null;
          email?: string | null;
          photo_url?: string | null;
          bio_en?: string | null;
          bio_ne?: string | null;
          display_order?: number;
          is_deleted?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name_en?: string;
          full_name_ne?: string;
          designation_en?: string | null;
          designation_ne?: string | null;
          specialization?: string | null;
          institution_en?: string | null;
          institution_ne?: string | null;
          province_id?: string | null;
          phone?: string | null;
          email?: string | null;
          photo_url?: string | null;
          bio_en?: string | null;
          bio_ne?: string | null;
          display_order?: number;
          is_deleted?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      committee_members: {
        Row: {
          id: string;
          full_name_en: string;
          full_name_ne: string;
          position_en: string;
          position_ne: string;
          category: string;
          email: string | null;
          phone: string | null;
          address_en: string | null;
          address_ne: string | null;
          photo_url: string | null;
          bio_en: string | null;
          bio_ne: string | null;
          display_order: number;
          status: string;
          is_deleted: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name_en: string;
          full_name_ne: string;
          position_en: string;
          position_ne: string;
          category?: string;
          email?: string | null;
          phone?: string | null;
          address_en?: string | null;
          address_ne?: string | null;
          photo_url?: string | null;
          bio_en?: string | null;
          bio_ne?: string | null;
          display_order?: number;
          status?: string;
          is_deleted?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name_en?: string;
          full_name_ne?: string;
          position_en?: string;
          position_ne?: string;
          category?: string;
          email?: string | null;
          phone?: string | null;
          address_en?: string | null;
          address_ne?: string | null;
          photo_url?: string | null;
          bio_en?: string | null;
          bio_ne?: string | null;
          display_order?: number;
          status?: string;
          is_deleted?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      site_settings: {
        Row: {
          id: string;
          key: string;
          value: string | null;
          description: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          value?: string | null;
          description?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          value?: string | null;
          description?: string | null;
          updated_at?: string;
        };
      };
      impact_statistics: {
        Row: {
          id: string;
          statistic_key: string;
          label_en: string;
          label_ne: string;
          value: string;
          suffix: string | null;
          icon: string | null;
          display_order: number;
          is_visible: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          statistic_key: string;
          label_en: string;
          label_ne: string;
          value: string;
          suffix?: string | null;
          icon?: string | null;
          display_order?: number;
          is_visible?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          statistic_key?: string;
          label_en?: string;
          label_ne?: string;
          value?: string;
          suffix?: string | null;
          icon?: string | null;
          display_order?: number;
          is_visible?: boolean;
          updated_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          patient_code: string;
          province_id: string | null;
          district: string | null;
          municipality: string | null;
          diagnosis_type: string;
          severity: string;
          date_of_birth: string | null;
          age_at_diagnosis: number | null;
          sex: string;
          blood_group: string | null;
          inhibitor_status: string;
          inhibitor_titer: string | null;
          treatment_status: string;
          treatment_centre_id: string | null;
          membership_status: string;
          emergency_contact_phone: string | null;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          patient_code: string;
          province_id?: string | null;
          district?: string | null;
          municipality?: string | null;
          diagnosis_type: string;
          severity: string;
          date_of_birth?: string | null;
          age_at_diagnosis?: number | null;
          sex: string;
          blood_group?: string | null;
          inhibitor_status?: string;
          inhibitor_titer?: string | null;
          treatment_status?: string;
          treatment_centre_id?: string | null;
          membership_status?: string;
          emergency_contact_phone?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          patient_code?: string;
          province_id?: string | null;
          district?: string | null;
          municipality?: string | null;
          diagnosis_type?: string;
          severity?: string;
          date_of_birth?: string | null;
          age_at_diagnosis?: number | null;
          sex?: string;
          blood_group?: string | null;
          inhibitor_status?: string;
          inhibitor_titer?: string | null;
          treatment_status?: string;
          treatment_centre_id?: string | null;
          membership_status?: string;
          emergency_contact_phone?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      membership_applications: {
        Row: {
          id: string;
          application_number: string;
          full_name: string;
          email: string;
          phone: string;
          province_id: string | null;
          district: string | null;
          membership_type: string;
          diagnosis_details: string | null;
          treatment_centre: string | null;
          blood_group: string | null;
          application_status: string;
          submitted_at: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          application_number: string;
          full_name: string;
          email: string;
          phone: string;
          province_id?: string | null;
          district?: string | null;
          membership_type?: string;
          diagnosis_details?: string | null;
          treatment_centre?: string | null;
          blood_group?: string | null;
          application_status?: string;
          submitted_at?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          application_number?: string;
          full_name?: string;
          email?: string;
          phone?: string;
          province_id?: string | null;
          district?: string | null;
          membership_type?: string;
          diagnosis_details?: string | null;
          treatment_centre?: string | null;
          blood_group?: string | null;
          application_status?: string;
          submitted_at?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      donations: {
        Row: {
          id: string;
          donor_name: string;
          email: string | null;
          phone: string | null;
          amount: number;
          currency: string;
          payment_method: string;
          transaction_reference: string | null;
          payment_status: string;
          donation_type: string;
          is_anonymous: boolean;
          receipt_number: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          donor_name: string;
          email?: string | null;
          phone?: string | null;
          amount: number;
          currency?: string;
          payment_method?: string;
          transaction_reference?: string | null;
          payment_status?: string;
          donation_type?: string;
          is_anonymous?: boolean;
          receipt_number?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          donor_name?: string;
          email?: string | null;
          phone?: string | null;
          amount?: number;
          currency?: string;
          payment_method?: string;
          transaction_reference?: string | null;
          payment_status?: string;
          donation_type?: string;
          is_anonymous?: boolean;
          receipt_number?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      support_requests: {
        Row: {
          id: string;
          request_type: string;
          name: string;
          phone: string;
          email: string | null;
          province_id: string | null;
          district: string | null;
          message: string;
          urgency: string;
          status: string;
          assigned_to: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          request_type: string;
          name: string;
          phone: string;
          email?: string | null;
          province_id?: string | null;
          district?: string | null;
          message: string;
          urgency?: string;
          status?: string;
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          request_type?: string;
          name?: string;
          phone?: string;
          email?: string | null;
          province_id?: string | null;
          district?: string | null;
          message?: string;
          urgency?: string;
          status?: string;
          assigned_to?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          table_name: string;
          record_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          table_name: string;
          record_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          table_name?: string;
          record_id?: string | null;
          old_data?: Json | null;
          new_data?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      view_public_patient_stats: {
        Row: {
          total_registered_patients: number;
          count_hemophilia_a: number;
          count_hemophilia_b: number;
          count_vwd: number;
          count_other_bleeding_disorders: number;
          count_severe: number;
          count_moderate: number;
          count_mild: number;
          count_inhibitor_positive: number;
          count_male: number;
          count_female: number;
          provinces_with_patients: number;
        };
      };
      view_patients_by_province: {
        Row: {
          province_id: string;
          province_name_en: string;
          province_name_ne: string;
          province_code: number;
          patient_count: number;
          hemophilia_a_count: number;
          hemophilia_b_count: number;
          severe_count: number;
        };
      };
    };
    Functions: {
      get_public_impact_metrics: {
        Args: Record<PropertyKey, never>;
        Returns: Json;
      };
      increment_resource_download: {
        Args: { res_id: string };
        Returns: void;
      };
    };
  };
}
